services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mathquestionsdb
    #TODO
    #volumes:

    ports:
      - "5432:5432"