services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mathexamplesdb
    volumes:
      - db-data:/var/lib/postgresql/data

    ports:
      - "5433:5432"
volumes:
  db-data: