spring:
#  PROD
  #  datasource:
  #    url: jdbc:postgresql://db:5433/mathexamplesdb
  #    username: mathpostgresqldb
  #    password: ${POSTGRES_PASSWORD}
  #    driverClassName: org.postgresql.Driver

# DEV
  datasource:
    url: jdbc:postgresql://localhost:5433/mathexamplesdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.hibernate.SQL: DEBUG